import Link from "next/link";
import { notFound } from "next/navigation";
import { marked } from "marked";
import { AudioButton } from "@/components/audio-button";
import { ViewTracker } from "@/components/view-tracker";
import { getDetailPageData } from "@/lib/quotes-data";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }) {
  const resolvedParams = await params;
  const heroName = decodeURIComponent(resolvedParams.hero);
  const skinName = decodeURIComponent(resolvedParams.skin);
  const item = getDetailPageData(heroName, skinName);

  if (!item) {
    return {
      title: "详情未找到",
    };
  }

  return {
    title: `${item.hero} · ${item.skin} · 三国杀台词鉴赏`,
    description: `${item.hero}「${item.skin}」的完整台词、音频与逐句解析。`,
  };
}

export default async function QuoteDetailPage({ params }) {
  const resolvedParams = await params;
  const heroName = decodeURIComponent(resolvedParams.hero);
  const skinName = decodeURIComponent(resolvedParams.skin);
  const item = getDetailPageData(heroName, skinName);

  if (!item) {
    notFound();
  }

  return (
    <main className="detail-shell">
      <ViewTracker hero={item.hero} skin={item.skin} />
      <section className="detail-header">
        <div className="detail-breadcrumbs">
          <Link href="/">首页</Link>
          <span>/</span>
          <Link href={`/hero/${encodeURIComponent(item.hero)}`}>{item.hero}</Link>
        </div>
        <div className="hero-title-area">
          <p className="eyebrow">QUOTE DETAIL</p>
          <h1>{item.hero} · {item.skin}</h1>
          <div className="sub-title">台词深度鉴赏与解析</div>
        </div>
      </section>

      <div className="detail-content">
        {item.skills?.map((skill) => (
          <section className="skill-section" key={`${item.hero}::${item.skin}::${skill.name}`}>
            <div className="skill-title">{skill.name}</div>
            <div className="quote-list">
              {skill.quotes?.map((quote, index) => {
                const explanationHtml = quote.explanation
                  ? marked.parse(quote.explanation)
                  : '<span style="color:var(--text-sec);font-style:italic">暂无解析</span>';

                return (
                  <article
                    className="quote-card"
                    key={`${item.hero}::${item.skin}::${skill.name}::${index}`}
                  >
                    <div className="quote-header">
                      <div className="quote-text">“ {quote.text} ”</div>
                      <AudioButton src={quote.audio} label={quote.text} />
                    </div>
                    <div
                      className="explanation-box"
                      dangerouslySetInnerHTML={{ __html: explanationHtml }}
                    />
                  </article>
                );
              })}
            </div>
          </section>
        ))}
      </div>

      <footer className="detail-footer">
        <p>Generated by DeepSeek V3.2</p>
      </footer>
    </main>
  );
}
